### ISSUE TITLE
Multi window support

### ISSUE THREAD

**Issue by Yamakaky** [ArjunNair/egui_sdl2_gl#11]
When detecting window resize events, it doesn't check which window is resized. When multiple windows are used, events from other windows will affect egui. The fix is to check like this: https://github.com/Yamakaky/gyromouse/blob/gui/src/backend/sdl/overlay.rs#L221-L225.

https://github.com/ArjunNair/egui_sdl2_gl/blob/main/src/lib.rs#L54-L57

**Comment by ArjunNair** [comment]
Good point! I'll integrate that fix asap.

**Comment by Yamakaky** [comment]
Sgtm!
