### ISSUE TITLE
Doesn't work with egui 0.9.0

### ISSUE THREAD

**Issue by derivator** [ArjunNair/egui_sdl2_gl#2]
See [changelog](https://github.com/emilk/egui/blob/master/CHANGELOG.md#090---2021-02-07---light-mode-and-much-more):

- Renamed Triangles to Mesh.
- The tesselator now wraps the clip rectangle and mesh in struct ClippedMesh(Rect, Mesh)

Looks like an easy enough fix at first glance... I could have a go at making a pull request if you don't feel like fixing it.

**Comment by ArjunNair** [comment]
Thanks for pointing it out. I'll put in the fix ASAP.

**Comment by derivator** [comment]
Thanks! Unrelated question: how would I actually integrate this into an existing application? I'm new to OpenGL, so I figured I would just call paint_jobs at the end of the frame and it would paint the GUI on top of everything else, but since you call gl::Clear there, that seems impossible?

**Comment by ArjunNair** [comment]
Fixed and then some more in v0.1.8.

**Comment by ArjunNair** [comment]
> 
> 
> Thanks! Unrelated question: how would I actually integrate this into an existing application? I'm new to OpenGL, so I figured I would just call paint_jobs at the end of the frame and it would paint the GUI on top of everything else, but since you call gl::Clear there, that seems impossible?

Hmm.. this is broken indeed. Can you open a new bug report please?
