### ISSUE TITLE
Make the gl part optional

### ISSUE THREAD

**Issue by Yamakaky** [ArjunNair/egui_sdl2_gl#23]
Example with egui_sdl2_gl + egui_wgpu: https://github.com/Yamakaky/gyromouse/blob/gui/src/backend/sdl/gui.rs

This mirrors https://github.com/hasenbanck/egui_example where the wgpu and winit crates are separated.

**Comment by ArjunNair** [comment]
There is a reason there is "gl" in the name of the package. :) The scope of this particular project is to demonstrate usage of egui with SDL2 and OpenGL in as simple and lightweight manner as possible. It wasn't and isn't meant to be a complex wrapper hybrid trying to cater to multiple backends and event processing libraries. There are other, better libraries already doing this for those who want a more flexible and complex library system (Macroquad for example).

**Comment by kaphula** [comment]
Just to be clear, can you pull this off somehow by using this repository without any additional changes. I see that the gyromouse is referencing your own fork of egui_sdl2_gl.

I'd like to be able to let SDL2 handle the events of egui and leave the rendering to wgpu in my application.

**Comment by ArjunNair** [comment]
Yes it should be possible with a bit of work because as I said this project was really supposed to be a demonstrate how to integrate a SDL2 _rendering_ solution with egui. I would suggest that it's easier to do a wgpu + egui solution and then use SDL2 for events.

**Comment by kaphula** [comment]
I created a [new crate / repository](https://github.com/kaphula/egui-sdl2-event) for this case.
