### ISSUE TITLE
Update Request to egui 0.18.1

### ISSUE THREAD

**Issue by d10sfan** [ArjunNair/egui_sdl2_gl#26]
0.18.1 was recently released, along with 0.17.0 a few months ago, which had some breaking changes. It looks like the main ones to worry about in that regard are (From the changelog - https://github.com/emilk/egui/blob/master/CHANGELOG.md)

For integrations:

    Output has now been renamed PlatformOutput and Context::run now returns the new FullOutput (https://github.com/emilk/egui/pull/1292).
    FontImage has been replaced by TexturesDelta (found in FullOutput), describing what textures were loaded and freed each frame (https://github.com/emilk/egui/pull/1110).
    The painter must support partial texture updates (https://github.com/emilk/egui/pull/1149).
    Added RawInput::max_texture_side which should be filled in with e.g. GL_MAX_TEXTURE_SIZE (https://github.com/emilk/egui/pull/1154).

**Comment by ArjunNair** [comment]
Working on this currently. Please be patient as there are many breaking changes. :)

**Comment by darthdeus** [comment]
@ArjunNair Is there a WIP branch somewhere? I've been thinking about tackling this myself, but probably doesn't make sense to start from scratch if you've already worked on it.

**Comment by ArjunNair** [comment]
@darthdeus I've created a branch named 'update_to_egui_0_18' with my current WIP. It's in a runnable state with some caveats:

-  There's something going on with the textures - they look terribly fuzzy.
-  The ui element event interaction is broken in some way. Some UI elements don't interact anymore and some behave in an odd manner. Dunno what's changed there as I haven't had a look at that side of things.
-  egui_demo_lib also is broken.

**Comment by pietervandermeer** [comment]
First of all, let me say that this crate is wonderful! It allows us to run EGUI and high performance GL on any SBC without nasty X11, window managers, etc!!

It seems there are a couple of interesting add-on crates for EGUI these days, but they unfortunately don't support egui_sdl2_gl.. And I just don't have skills or time to port them.. Is there an effort to keep up with the latest EGUI 0.20? Sorry for asking.. I know this is all free software.

**Comment by ArjunNair** [comment]
Thanks for the kind words. I'm unfortunately not finding the time to keep up with the pace of egui releases. I do plan to take a look at it in more depth when I have some time on my hands but I can't say when that's likely to happen given my current work schedule.

**Comment by pietervandermeer** [comment]
Understood. Once again, thanks for your awesome work.
