### ISSUE TITLE
Unclear how to integrate with existing application

### ISSUE THREAD

**Issue by derivator** [ArjunNair/egui_sdl2_gl#3]
For someone new to OpenGL it is unclear how to integrate this with an existing application. Since `paint_jobs` calls `gl::Clear(gl::COLOR_BUFFER_BIT)`, it will overwrite anything drawn before it. Notably, [egui_glium does this, too](https://github.com/emilk/egui/blob/a859b2a26eb7fd306f4028f0158bce201306ca7d/egui_glium/src/painter.rs#L109), so there might be a good reason, but to a newcomer it's unclear how this is supposed to work. It might be possible to paint the gui first and use depth testing to draw your content _under_ the gui, but if this is the intended usage it would be nice if it was documented somewhere how to do that.

**Comment by ArjunNair** [comment]
I've made the Clear optional. If paint_jobs is passed a bg_color, then the painter will clear the background and set the color for you. If you don't, then you must clear the background somewhere in the render loop. I've updated the example to render an OpenGL triangle (which has no knowledge of egui or the backend whatsoever), over which egui is overlaid seamlessly. The comments in the example code should be helpful in this regard. HTH!
