### ISSUE TITLE
Do you have any plans to support SDL2 and Vulkan?

### ISSUE THREAD

**Issue by iddm** [ArjunNair/egui_sdl2_gl#34]
Hi! I was wondering if you were going to also add Vulkan support later. Preferably, using the `ash` crate.

**Comment by ArjunNair** [comment]
Apologies for the late reply. No, I don't have plans to support Vulkan. There is a reason why gl is in the name of this project. :) You may want to check out [this project](https://github.com/ComLarsic/egui_sdl2_platform) if you wish to plugin a renderer other than gl.
