### ISSUE TITLE
Doesn't pass egui color test

### ISSUE THREAD

**Issue by derivator** [ArjunNair/egui_sdl2_gl#4]
![Captura de pantalla de 2021-02-28 14-10-52](https://user-images.githubusercontent.com/2171264/109420487-14441a80-79d3-11eb-866c-da3448e95924.png)
The gradients should all match up seamlessly.
To reproduce: 
```rust
let mut egui_test = egui_demo_lib::ColorTest::default();
egui::Window::new("Test").show(&egui_ctx, |ui| {
    let mut none = None;
    egui_test.ui(ui,&mut none);
});
```

I think the problem might be with the [srgb conversion/blending code](https://github.com/ArjunNair/egui_sdl2_gl/blob/741b818e61ff8926771cba5511fcc8b328c5176d/src/painter.rs#L101), but I'm not sure.

**Comment by ArjunNair** [comment]
Thanks for pointing that out! I've put in a fix which appears to correct the color space, at least on my Mac. But if you can confirm, I will go ahead and mark this as fixed.

**Comment by derivator** [comment]
Looks fixed to me! :+1:
