### ISSUE TITLE
own gl Textures are not displayed for some reason

### ISSUE THREAD

**Issue by luca-jt** [ArjunNair/egui_sdl2_gl#40]
i am not shure if this is a mistake on my side. i am also not entirely familiar with the internal ways this crate operates. when i try to create  my own gl texture an render a cube with that texture on it, for some reason some user textures i created earlier with the painter are being rendered on the cube. is it possible that this has something to do with the way this backend operates? it is really strange because when i draw my cube mesh i literally just set the active texture, bind the buffer and set the uniform for the shader. thats all i do. the texture that is displayed also varies from app launch to app launch, which is even more strange.

**Comment by luca-jt** [comment]
i am not shure if this is a mistake on my side. i am also notentirely familiar with the internal ways this crate operates. when i try to create  my own gl texture an render a cube with that texture on it, for some reason some user textures i created earlier with the painter are being rendered on the cube. is it possible that this has something to do with the way this backend operates?

**Comment by ArjunNair** [comment]
Would it be possible to share your code, or even better, a test project with the issue?

**Comment by luca-jt** [comment]
it is quite a big project - a group of people have been working on it for like a month. it is not open source sadly. i could create a little test project to reproduce the issue but that would take some time.
I am creating the texture manually and not with the painter. it seems the texture i am creating has the same id as some other user_texture from the painter, although i am not shure if the TextureId is the "same" Id as the gl texture id or some other id system.
here is a little snippet that might help:

i load the texture:
`pub fn load_texture(file_name: &str) -> GLuint {
    let mut tex_id = 0;

    let texture: Image<u8>;
    match stb_image::image::load_with_depth(get_texture_path(file_name), 3, false) {
        LoadResult::ImageU8(im) => { texture = im; }
        _ => { panic!("error reading texture") }
    }

    unsafe {
        gl::GenTextures(1, &mut tex_id);
        gl::BindTexture(gl::TEXTURE_2D, tex_id);
        gl::TexImage2D(gl::TEXTURE_2D, 0, gl::RGB as GLint, texture.width as GLint, texture.height as GLint, 0, gl::RGB, gl::UNSIGNED_BYTE, texture.data.as_ptr() as *const GLvoid);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MAG_FILTER, gl::NEAREST as GLint);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MIN_FILTER, gl::NEAREST as GLint);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_S, gl::REPEAT as GLint);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_T, gl::REPEAT as GLint);
    }

    tex_id
}
`
i create the cube and draw it every frame:
`impl Mesh for Cube {
    fn new(vertex_data: VertexData, uv_data: VertexData) -> Self {
        let mut vao = 0;
        let mut vbo = 0;
        let mut tbo = load_texture("wall.png");
        let program: ShaderProgram;

        unsafe {
            program = ShaderProgram::new("./res/shaders/vs.glsl", "./res/shaders/fs.glsl");

            gl::GenVertexArrays(1, &mut vao);
            gl::GenBuffers(1, &mut vbo);
            gl::GenBuffers(1, &mut tbo);

            gl::BindVertexArray(vao);
            gl::BindBuffer(gl::ARRAY_BUFFER, vbo);
            gl::BufferData(
                gl::ARRAY_BUFFER,
                (vertex_data.len() * mem::size_of::<GLfloat>()) as GLsizeiptr,
                mem::transmute(vertex_data.get(0).unwrap()),
                gl::DYNAMIC_DRAW,
            );
            gl::BindBuffer(gl::ARRAY_BUFFER, tbo);
            gl::BufferData(
                gl::ARRAY_BUFFER,
                (uv_data.len() * mem::size_of::<GLfloat>()) as GLsizeiptr,
                mem::transmute(uv_data.get(0).unwrap()),
                gl::DYNAMIC_DRAW,
            );
        }

        Cube { program, vao, vbo, vertex_data, tbo }
    }


    fn draw(&self, camera: &CameraConfig) {
        unsafe {
            gl::BindVertexArray(self.vao);
            gl::UseProgram(self.program.id);
            gl::UniformMatrix4fv(self.program.mvp_unif, 1, gl::FALSE, &camera.mvp[0]);
            gl::ActiveTexture(gl::TEXTURE0);
            gl::BindTexture(gl::TEXTURE_2D, self.tbo);
            gl::Uniform1i(self.program.sampler_unif, 0);

            gl::BindBuffer(gl::ARRAY_BUFFER, self.vbo);
            gl::VertexAttribPointer(
                self.program.pos_attr as GLuint,
                3,
                gl::FLOAT,
                gl::FALSE as GLboolean,
                0,
                ptr::null(),
            );
            gl::EnableVertexAttribArray(self.program.pos_attr as GLuint);

            gl::BindBuffer(gl::ARRAY_BUFFER, self.tbo);
            gl::VertexAttribPointer(
                self.program.tex_attr as GLuint,
                2,
                gl::FLOAT,
                gl::FALSE as GLboolean,
                0,
                ptr::null(),
            );
            gl::EnableVertexAttribArray(self.program.tex_attr as GLuint);

            gl::DrawArrays(gl::TRIANGLES, 0, (self.vertex_data.len() / 3) as GLsizei);
            gl::DisableVertexAttribArray(self.program.pos_attr as GLuint);
            gl::DisableVertexAttribArray(self.program.tex_attr as GLuint);
            gl::BindBuffer(gl::ARRAY_BUFFER, 0);
            gl::BindVertexArray(0);
        }
    }
}
`
my loop looks like this:
`self.render_panel(start_time);
  self.draw_egui_elements(&mut frame_start_time); // draws some ui stuff
  if !self.process_output_success() { // this is just the same as the triangle example
      break 'running;
  }
`
this is the render panel function:
`clear_gl_screen();
  if self.asv.flags.playing_level {
      if self.asv.settings.use_3d_rendering {
          self.meshes.draw_all(&self.asv.camera_config); // this is where the cube is drawn, there is just one mesh at the moment
      } else {
          // do some stuff with an rgba buffer
      }
  }
  self.painter.update_user_texture_data(self.board_tex_id, &self.srgba_buffer);
  for idx in 0..NUM_OF_SPRITES {
      self.painter.update_user_texture_data(self.asv.shop_tex_ids[idx].unwrap(), &self.asv.shop_skins[idx]);
  }
  self.egui_state.input.time = Some(start_time.elapsed().as_secs_f64());
  self.egui_ctx.begin_frame(self.egui_state.input.take());
  `
  i hope this helps a bit. all the other user textures i am creating with the painter are created at app launch just before the cube is created.

**Comment by luca-jt** [comment]
something that is also interesting that i just found out is that this also happens with egui::Image 's i draw to the ui. there is an image that is displayed at app launch and when i render the cube and i have disabled some of the user textures that image gets rendered onto the cube.

**Comment by ArjunNair** [comment]
Looks like the egui also maintains its own set of texture id's that are overlapping with the one's you generated. Are you using the new_user_texture method(s) of painter in any place in your code? IAC, let me look into this further.

**Comment by luca-jt** [comment]
yes i am using the ``painter.new_user_texture`` method 6 times. it is very similar to the triangle example with the srgba buffer.

**Comment by luca-jt** [comment]
this is the way it looks:
![Screenshot 2024-05-21 132506](https://github.com/ArjunNair/egui_sdl2_gl/assets/82292985/03685674-07bb-4d97-8959-4d8f1711dbd6)
![Screenshot 2024-05-21 132433](https://github.com/ArjunNair/egui_sdl2_gl/assets/82292985/2dfd2bf9-5f72-4805-af9c-8a44c0cf1c82)
there is a user texture for just some test sprite image, and when i render the cube thats what i see. (note: the uv data is not properly set, thats why the cube texture is not correct)
interesting: the texture rendered onto the cube changes with every app launch. seems like some dynamic id stuff idk.

**Comment by ArjunNair** [comment]
Alternately, instead of generating the texture id yourself, could you use the new_user_texture method(s) of painter to give you the texture id instead? This method requires you to pass in the size of texture, the texture data (raw bytes loaded into memory) and the required filtering.

So basically, instead of:
`pub fn load_texture(file_name: &str) -> GLuint {
    let mut tex_id = 0;

    let texture: Image<u8>;
    match stb_image::image::load_with_depth(get_texture_path(file_name), 3, false) {
        LoadResult::ImageU8(im) => { texture = im; }
        _ => { panic!("error reading texture") }
    }

    unsafe {
        gl::GenTextures(1, &mut tex_id);
        gl::BindTexture(gl::TEXTURE_2D, tex_id);
        gl::TexImage2D(gl::TEXTURE_2D, 0, gl::RGB as GLint, texture.width as GLint, texture.height as GLint, 0, gl::RGB, gl::UNSIGNED_BYTE, texture.data.as_ptr() as *const GLvoid);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MAG_FILTER, gl::NEAREST as GLint);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MIN_FILTER, gl::NEAREST as GLint);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_S, gl::REPEAT as GLint);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_T, gl::REPEAT as GLint);
    }

    tex_id
}`

You can try just:
`pub fn load_texture(file_name: &str) -> egui::TextureId {
    let texture: Image<u8>;
    match stb_image::image::load_with_depth(get_texture_path(file_name), 3, false) {
        LoadResult::ImageU8(im) => { texture = im; }
        _ => { panic!("error reading texture") }
    }
    
    // need the painter reference here.
    let tex_id = painter_ref.pub fn new_user_texture_rgba8(
        (texture.width as usize, texture.width as usize),
         // some way to convert to Vec here from Image<u8>
        texture.to_vec(),
        false,
    )
}`

To use the the egui texture id (which isn't a gl texture id), you need to ask painter to get you the actual texture info using this id:
`if let Some(Texture {
            gl_id: Some(texture_id), // this is an actual gl id
            ..
        }) = self.textures.get(&id) 
{
      // use gl_id for opengl stuff.
}
`

**Comment by ArjunNair** [comment]
> yes i am using the `painter.new_user_texture` method 6 times. it is very similar to the triangle example with the srgba buffer. i am creating all the user textures right before i create the cube.

I don't believe you can mix and match generating your id's with using new_user_texture because that maintains its own set of texture id's which can lead to id collision.

**Comment by luca-jt** [comment]
Thank you.
The Texture struct is not public so i cant use it anyway like this
```rs
if let Some(Texture {
            gl_id: Some(texture_id), // this is an actual gl id
            ..
        }) = self.textures.get(&id) 
{
      // use gl_id for opengl stuff.
}
```

**Comment by luca-jt** [comment]
i have recreated the same issue with exerpts from the big project by modifying the triangle example. it doesnt use my own user textures but just the sin wave texture. idk why but that makes the cube appear with weird text on it. it doesnt even load any texture at all. seems like a gl problem. i ont know but maybe this helps.
[https://github.com/luca-jt/egui_sdl2_gl-cube_test](url)

**Comment by luca-jt** [comment]
i looked through the painter.rs code and noticed some things: (i dont know if that might have anything to do with this - i am no expert.)
i immediately detach and delete my shaders when i link the program. you do that after creating the buffers etc. i also use rgb format and not rgba.

**Comment by luca-jt** [comment]
omg i fixed it. i am so embarrassed. it was my mistake. i used the wrong id for the texture. the ids for the texture uv data and the actual texture id got mixed up.

**Comment by ArjunNair** [comment]
Nice! All is well and that ends well.
