### ISSUE TITLE
SDL2 Canvas + EGUI?

### ISSUE THREAD

**Issue by miwarnec** [ArjunNair/egui_sdl2_gl#42]
Hey there, thanks for the amazing work with this crate!
Any idea how I could show egui in a SDL2 canvas (2D pixels)?
It works well for 3D, but for 2D I am just seeing a black screen.

I can mouse over the UI elements and see the cursor change, but it only renders everything completely black.

**Comment by ArjunNair** [comment]
Someone on reddit (surprisingly?) mentioned the same issue here: https://www.reddit.com/r/rust/comments/q0rxh6/help_im_trying_to_make_egui_sdl2_gl_and_sdl2s/

Can you try the canvas.render_flush() method and see if it works as suggested by the OP?

**Comment by miwarnec** [comment]
Oh wow @ArjunNair you actually replied :)
Thanks for sharing, doesn't seem to solve it just yet.
Any chance I could pay you to add a small sdl2 + egui + canvas demo?
You are probably much more familiar with this stuff, I've only been using SDL for 2 days.

**Comment by ArjunNair** [comment]
I don't need any payments however I do have limited time for any new explorations. I could try rustling up a demo but it will take me a few days given how much I have going on currently. However, if you're willing to share your current project or a smaller section of it, it will help reduce the turnaround time.

**Comment by ArjunNair** [comment]
I have been unable to get this working either. I either get a blank screen or I see the canvas but not both together. Seeing that the reddit link I posted earlier was by @GuillaumeGomez, I wonder if he can shed some light on how he got it working?

@miwarnec Any particular reason why you want to mix SDL2 Canvas and opengl? One suggestion I have is, don't use SDL2 canvas. Instead use an OpenGL texture to set pixels (see the 'mix' example) and use that as your background. Egui window can be overlaid on that - just like the 'mix' example.

**Comment by ArjunNair** [comment]
Closing as there's no further info on this.
