### ISSUE TITLE
Clarify OpenGL version requirements

### ISSUE THREAD

**Issue by SkyLeite** [ArjunNair/egui_sdl2_gl#43]
Running the example program in an embedded device gives me the following error:

`0:1: P0007: Language version '150' unknown, this compiler only supports up to version '320 es'`

Would it be possible to add the minimum required OpenGL version to the README? As a separate request, would it be possible to drop the required version so that it's compatible with `320 es`, or provide a workaround?

**Comment by ArjunNair** [comment]
Which example are you trying to run? 

You can try recompiling the example to use the ShaderVersion::Adaptive version and running them. The Adaptive version supports GLES but I've been unable to confirm that personally.

To change the shader version in the example code, look for a line that's something like:
`let (mut painter, mut egui_state) =
        egui_backend::with_sdl2(&window, ShaderVersion::Default, DpiScaling::Default);`

The second parameter to with_sdl2 should be changed to ShaderVersion::Adaptive. Build and run!

**Comment by SkyLeite** [comment]
I'm trying to run the basic example. And after reading your comment I noticed the shader thing is mentioned in the code itself :p 

Setting ShaderVersion to ShaderVersion::Adaptive worked perfectly. Thanks!
